### PR TITLE
Add warning when viewing an old version of the guides

### LINKED ISSUE #506: Add warning to page if it is an old version
This should be done with JavaScript. #114 is a PR that starts this work but has stalled out. It would be great if somebody could pick up where @wagenet left off (or if @wagenet wants to pick that up, that would be great too!).

### PR DESCRIPTION
**Pull request by mozeryansky**
Closes #506

With contributions from @acorncom and @wagenet
Thanks to @locks and @michaelrkn for feedback

(cherry picked from commit 676c867d9395374d26f4589eff0fd46d5e28fb63)

### CODE REVIEW

**Comment by mozeryansky** [comment]
This is reference to my open issue #1122 

I verified the changes would work on my local machine, but I am unsure how the constant in `_versions.js.erb` will be replaced: CURRENT_REVISION_WILL_APPEAR_HERE_WHEN_DEPLOYED.

This change was done using a cherry pick of the original commit that fixed the issue in v2.0.0.
Switch to the versioned branch:
`git checkout v1.13.0`
Cherry pick the original commit
`git cherry-pick -x 676c867d9395374d26f4589eff0fd46d5e28fb63 --strategy-option theirs`

**Comment by mozeryansky** [comment]
If this works, then I can test it out in the other previous versions and send pull requests.

**Comment by acorncom** [comment]
@mozeryansky Not sure if you're still around and able to help with these things.  Since you sent this in I've grown comfortable with updating old docs, so would love to take you up on putting in these changes to the older docs if you're still willing to ...

**Comment by mozeryansky** [comment]
I've moved on to another project. I'm glad you'll be looking into old docs, almost all my google hits were pages within 1.x when I was working on 2.0.

**Pull request closed without merging**
