### PR TITLE
Fixed broken URL to template actions

### PR DESCRIPTION
**Pull request by t1mmen**
From http://guides.emberjs.com/v1.10.0/components/handling-user-interaction-with-actions/, the link to actions points to http://guides.emberjs.com/v1.10.0/components/templates/actions

### CODE REVIEW

**Comment by karelvuong** [comment]
Seems to be an issue with the relative path. There is another broken link on the same page at the bottom, see: [Actions section](http://guides.emberjs.com/v1.10.0/components/templates/actions) and pretty much everywhere else. :cry: 

screen shot 2015-03-09 at 4 11 00 pm

**Comment by t1mmen** [comment]
You're right @karelvuong – there are a TON of broken links everywhere. I'll close this PR, as it really doesn't do much good to fix one link manually (I'm guessing this is a build issue anyway?)

**Comment by trek** [comment]
It's unrelated to builds. Someone needs to audit all the links.

**Comment by Dhaulagiri** [comment]
Opened #41 for this

**Pull request closed without merging**
