### PR TITLE
Use run loop in the example code describing the use of the run loop

### PR DESCRIPTION
**Pull request by ksin**
Tiny fix. Referring to this page of the documentation:
http://guides.emberjs.com/v1.10.0/understanding-ember/run-loop/

### CODE REVIEW

**Comment by locks** [comment]
Hm, this whole section is rather strange. I think the goal was to kind of say that there's an implicit runloop for Ember and that that code block will get scheduled in it, but it ends up confusing.

@michaelrkn are we keeping this section? might need a review and a check for update-ness.

**Comment by michaelrkn** [comment]
I don't know if we're keeping it. It feels like maybe it's outside the scope of the guides... does the average Ember developer need to know about the run loop in order to successfully write Ember apps? Any thoughts, @trek?

**Comment by ksin** [comment]
@michaelrkn As an average Ember developer, my input is that I would like to see as much documentation on it as possible. I feel like anyone building a non-trivial Ember app will quickly run into problems where understanding the run loop better will be very helpful.

**Comment by michaelrkn** [comment]
Thanks for the input, @ksin! I definitely agree it should be documented - the question is, should it be covered in the guides or just elsewhere (eg API docs)?

**Comment by locks** [comment]
@ksin thank you for raising the issue, but this needs more discussion. I've opened a meta issue and tagged you and @michaelrkn if you want to get looped in.

**Comment by ksin** [comment]
Thanks @locks . Hope to get it resolved soon. :)

**Pull request closed without merging**
