### PR TITLE
Update line break guidelines

### PR DESCRIPTION
**Pull request by michaelrkn**

### CODE REVIEW

**Comment by rtablada** [comment]
:aww:

**Comment by locks** [comment]
:-1:

**Comment by rtablada** [comment]
@locks more of a guideline for when to line break. It's not going to be enforcable automatically, but the 120 is already not enforced. This gives an idea of when to line break.

The line breaks will also help in git diff and merge conflict which can lead to a hard time contributing to docs.

**Comment by michaelrkn** [comment]
@acorncom what are your thoughts?

**Comment by acorncom** [comment]
I'm fine with merging it, but don't like the idea of simply out-voting people. @locks, after further thought are you ok with merging this?

**Comment by locks** [comment]
No, but I've been out-voted. :cry: :cry:

**Pull request merged**
