### PR TITLE
Remove composing components

### PR DESCRIPTION
**Pull request by michaelrkn**
@trek was right. This would make a nice blog post but doesn't belong in the Guides. Especially with the new closure actions guide coming soon.

### CODE REVIEW

**Comment by locks** [comment]
I feel like we should be putting this somewhere before killing it from the guides. cookbook?

**Comment by michaelrkn** [comment]
Cookbooks sounds good to me! @greyhwndz you got any interest in moving this content over there?

**Comment by greyhwndz** [comment]
@michaelrkn kinda tight on my end but I would like to look into this in a day or 2. Thanks for pinging me :)

**Comment by greyhwndz** [comment]
@michaelrkn & @locks: just added this to the Cookbook

**Comment by locks** [comment]
@greyhwndz appreciated

**Pull request merged**
