### PR TITLE
[WIP] Check for unused spelling exceptions, resolves #1105

### LINKED ISSUE #1105: Keep spell checker exceptions file clean
We should have a script that's run, preferably with the tests, to make sure that every word in the spell checker exception file is actually used.

While this may lead to some churn in the future if said word is reintroduced by another commit, I think the benefit of making the writer more aware outweighs it.

### PR DESCRIPTION
**Pull request by stevekinney**
This is a first pass at addressing #1105. It does a quick scan through the documentation for a particular word. If it is not found, the expectation fails and the developer is notified as to which word was not found.

To my surprise, scanning the entire set of guides is relatively quick. I tried it with 1,000 words and there was no performance issue.

I also removed all of the unused spelling words.

### CODE REVIEW

**Comment by locks** [comment]
Can you rebase and fix the failing test please?

**Comment by stevekinney** [comment]
Yup. I'm having a little issue where when I remove words that are not in the actual `./source` directory, the build process is failing because of the misspelled word. I'm wondering if it's checking an outdated index. I'm going to take a look at it a little deeper this afternoon.

For example, if you `grep` or `ag` for `actionhttp`. It's no where in any of the markdown files. But, if you remove it from the list, the spell checker fails.

**Comment by acorncom** [comment]
@stevekinney Any updates here?  Would love to get this merged :-)

**Comment by locks** [comment]
@stevekinney can you give this some TLC?

**Comment by acorncom** [comment]
I'm going to close this for now as part of a pending PR cleanup.  @stevekinney if you want to work on this more, happy to re-open it! :-)

**Pull request closed without merging**
