### PR TITLE
Rework testing components guide

### PR DESCRIPTION
**Pull request by HeroicEric**
- Tries to match the style/format of other testing guides
- Tries to make examples easier to follow
- Removes unnecessary template imports

### CODE REVIEW

**Comment by bf4** [comment]
Nice.

**Comment by michaelrkn** [comment]
@rwjblue @trek any reason not to merge this in?

**Comment by HeroicEric** [comment]
@runspired thanks for the feedback. Haven't looked at this in a while. I'll check it out tomorrow.

**Comment by michaelrkn** [comment]
Hey @HeroicEric, we are going re-cut the 1.13 release, hopefully tomorrow - if you have time tonight or in the morning to finish this up, it would be awesome to get this merged in before we cut!

**Comment by HeroicEric** [comment]
@michaelrkn I think this can definitely still use a lot of work but it is able to be merged now and I think that it's a little bit of an improvement

**Comment by michaelrkn** [comment]
Awesome, thanks! Maybe you can open an issue outlining what needs to be done next.

**Pull request merged**
