### PR TITLE
Tutorial: Highlight lines of interest.

### PR DESCRIPTION
**Pull request by zodiac403**
Hi there,

just a minor formatting suggestion. When working through *Routes and Templates*, I found two code snippets, that only have to be modified in a few lines. How about highlighting the relevant lines?

### CODE REVIEW

**Comment by toddjordan** [comment]
good idea.  we have a pretty big pr today landing in #1818.  Let's re-evaluate once that lands.  if the same issue exists will merge on that.

**Comment by zodiac403** [comment]
Hi @toddjordan,
OK, after syncing my branch with the master again, I see that one change already found its way into the tutorial:
https://github.com/emberjs/guides/blame/master/source/localizable/tutorial/routes-and-templates.md#L149

So it's one small change remaining. If you need anything else from my side, please let me know.

**Comment by locks** [comment]
Merging manually so I can squish commits.

**Comment by toddjordan** [comment]
Thanks @zodiac403 !
@homu r+

**Comment by toddjordan** [comment]
lol, didn't refresh see @locks merge

**Pull request merged**
