### PR TITLE
Create Creating a New App

### PR DESCRIPTION
**Pull request by rovo79**
Migrated this content from the Getting Started-> Ember CLI page to a new page under Tutorial.

### CODE REVIEW

**Comment by locks** [comment]
I'm not sure this is a change we want to make, but at any rate the change should be made in a single PR so we don't lose the text in git.

**Comment by rovo79** [comment]
I agree. Just trying to point out that content seems to belong to the Tutorial section, and not the Getting Started section.

**Comment by acorncom** [comment]
@rovo79 Thanks for the note on this.  We're in the process of cleaning things up there (the tutorial section is still in the early stages of being re-written), so will close this.  Do let us know if you find any other bugs though!

**Comment by rovo79** [comment]
Thanks so much. Overall, I think the guides coupled with CLI did an amazing job onboarding me quickly.

**Pull request closed without merging**
