### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by gabzilla**
Added an additional clarification of the red/green syntax highlighting under organization.

### CODE REVIEW

**Comment by locks** [comment]
Hm, I feel like this explanation could benefit from a couple examples, maybe under its own heading.

**Comment by gabzilla** [comment]
okay! That sounds like a great idea i'll do that 😄

**Comment by locks** [comment]
Hi @gabzilla, will you have some time soon so we can knock this one down?

**Comment by locks** [comment]
Hi @gabzilla, I'm closing this due to inactivity. I've queued it up on our work queue so not to forget it. If you find yourself with time, contact us again!

**Pull request closed without merging**
