### PR TITLE
Changed double quotes to single quotes to avoid confusion on View - INSE...

### PR DESCRIPTION
**Pull request by bradware**
@locks do you mind taking a look at this pr?

### CODE REVIEW

**Comment by locks** [comment]
@bware225 I'm actually not sure what the styleguide is here. /ping @trek

**Comment by trek** [comment]
We should standardize on one for sure, but I'm not sure what confusion having both right now would cause.

**Comment by bware225** [comment]
@trek For JS beginners like myself, I was confused if one was needed over the other in certain situations. Not a huge deal just figured it would be good to pick one

**Comment by locks** [comment]
@bradware since the views section of the guide is gone can you close this? sorry it didn't make it in time!

**Comment by michaelrkn** [comment]
This can be closed. cc @rwjblue

**Pull request closed without merging**
