### PR TITLE
Use shared styles gem

### PR DESCRIPTION
**Pull request by namack**
This PR extracts base and component styling code to the [emberjs_website_styles gem](https://rubygems.org/gems/emberjs_website_styles) as the first step in sharing style code between the website and guide repos.

There should be no visual changes from the website perspective.

https://github.com/emberjs/website/pull/2497

### CODE REVIEW

**Comment by locks** [comment]
Hi @namack, I consider it bad etiquette to publish a gem containing project resources without first consulting and coordinating with us, regardless of intentions. A git dependency would have done just as well for the sake of the PR.
That issue aside, there's also the matter that we are already coordinating work to tweak some of the styling throughout the pages, as well as possibility moving off middleman/Ruby. It would be best to get in touch with @ryanlabouve regarding styling.

**Comment by acorncom** [comment]
@locks regarding the gem, @namack ran that by me privately before he went that route. If that was out of line, it was my fault and not his. I explained to him that we were aiming to move away from middleman and that it might be thrown away after a month or two. However he could see it being useful right now and hadn't published a gem before, so thought he'd use it as a learning experience. :-)

**Comment by namack** [comment]
Yep! Just wanted to give it a shot and contribute however I can.

**Comment by locks** [comment]
We've hashed it out privately but I want to leave on public record that we are looking forward for @namack's contributions and the miscommunication has been rectified.

**Comment by namack** [comment]
@homu Since @ryanlabouve and @locks already had a plan forward for sharing styles between the guides and website, I'm going to close this PR. I'll make sure to coordinate with @ryanlabouve regarding any further styling work.

**Pull request closed without merging**
