### PR TITLE
correct url to action-bubbling.png

### PR DESCRIPTION
**Pull request by nonmanifold**
URL to action-bubbling.png should be relative, not absolute

### CODE REVIEW

**Comment by wagenet** [comment]
@rwjblue was this cherry-picked into the individual branches as well?

**Comment by rwjblue** [comment]
Nope, it was only updated on master.

**Comment by wagenet** [comment]
@rwjblue this seems like a regression to the 1.10 guides. I'd think we should fix regressions when they happen.

**Comment by rwjblue** [comment]
I do not disagree, someone should PR this against v1.10 and v1.11 branches then.

**Comment by wagenet** [comment]
@nonmanifold could you do that?

**Comment by nonmanifold** [comment]
@wagenet I have no idea how to do it, sorry.

**Pull request merged**
