### PR TITLE
Fix incorrect reference to `rentalUnit` variable.

### PR DESCRIPTION
**Pull request by CodingItWrong**
Split off from #1515.

This paragraph references a `rentalUnit` variable that's passed into the component, but the correct name of the variable is `rental`. This updates the paragraph to match the code.

A clearer option could be to leave the paragraph as-is, and *actually* name the variable `rentalUnit` in the code here and in `model-hook.md`.

### CODE REVIEW

**Comment by toddjordan** [comment]
@CodingItWrong I think changing the code back to rentalUnit would be easier for the reader to understand.  Do you mind updating the PR with what you suggest?

**Comment by CodingItWrong** [comment]
Will do!

**Comment by CodingItWrong** [comment]
@toddjordan When I looked into making that change, the simplest way to do it seemed to be to rename the loop variable, and keep the component attribute the same. Because the page says we simply _move_ the rental display details from `index.hbs` to `rental-listing.hbs`, it seems simplest to keep the variable names the same in both of those places. So the smallest change is just to change the loop variable that occurs in `index.hbs` to be different. Let me know your thoughts!

**Comment by toddjordan** [comment]
Sounds good, now that you've changed the code, you can change the text back...
"... and assign each `rentalUnit` as the `rental` ..."

**Comment by CodingItWrong** [comment]
@toddjordan Sorry about that; it should be correct now.

**Comment by toddjordan** [comment]
LGTM. Thanks for contribution!

**Comment by toddjordan** [comment]
@homu r+

**Pull request merged**
