### PR TITLE
Miscellaneous edits

### PR DESCRIPTION
**Pull request by CodingItWrong**
Word choice, formatting, and accuracy.

### CODE REVIEW

**Comment by locks** [comment]
Hi @CodingItWrong, couple of points:

* You should only [change the source](https://github.com/emberjs/guides/blob/master/CONTRIBUTING.md#style-guide) file, not the translations
* There are too many different changes in the same PR, could you break it up into different PRs to make it easier for us to review it?

Can you address this please? I specifically want to merge the `currentURL` and the `http://` links parts, but some of the other changes need further discussion.

**Comment by CodingItWrong** [comment]
Absolutely, will do it shortly!

**Comment by CodingItWrong** [comment]
@locks OK, I've split many of these into separate PRs (#1517, #1518, #1519, #1520, #1521, #1522).

The others are I think non-controversial grammar edits; would you like those in a single PR, or split out per change?

**Comment by acorncom** [comment]
@CodingItWrong I think all non-controversial grammar edits could go in a single PR, thanks

**Pull request closed without merging**
