### PR TITLE
Modified to match the HTML specified in templates

### PR DESCRIPTION
**Pull request by morhook**
The guide specifies a different HTML (in the screenshot there's only a `<ul><li>`). Replaced with real output

### CODE REVIEW

**Comment by locks** [comment]
Hi @morhook, thanks for your contribution. Do you have access to Google Chrome so the screenshots are consistent throughout the tutorial?

**Comment by morhook** [comment]
Hi @locks ! I've got a Chrome in Ubuntu. I can upload that screenshot to have a more consistent look

**Comment by locks** [comment]
@morhook can you squash the commits before we merge please?

**Comment by morhook** [comment]
Sure @locks ! Squashed!

**Comment by locks** [comment]
@homu r+

**Pull request merged**
