### PR TITLE
[WIP] Setup for linting JS in our markdown files

### PR DESCRIPTION
**Pull request by mtthgn**
This PR sets up our test suite to make sure the JS in our markdown files is up to Ember's standard. We accomplish this by running a linter with effectively the same `.jshintrc` as the ember.js repo.

Tests are failing on purpose right now so that we can have a conversation about the following:

- What should the output look like when it fails?
- Should there be a test for each markdown file? Or should we instead have one test that makes sure _all_ js code passes?

Things to do:

- [x] Lint against a JS string, rather than an entire file
- [ ] Extract snippets from Markdown files
- [ ] Run linter against said snippets
- [ ] update gemfile to point to the original jshint gem provided
      [This PR](https://github.com/damian/jshint/pull/34) gets merged

### CODE REVIEW

**Comment by michaelrkn** [comment]
Thanks for getting this going, @mtthgn!

I think the most straightforward way to achieve this goal is to raise an exception if code on a page doesn't pass linting. This approach is used to [prevent dead links in the table of contents](https://github.com/emberjs/guides/blob/master/lib/toc.rb#L32). That way, the page author will get immediate feedback in their development environment if there's a problem, and the CI build will fail if somehow bad code does get pushed.

**Comment by mtthgn** [comment]
@michaelrkn Where would you suggest doing that for the markdown files? I'm not very familiar with middleman, but I can't find _where_ I'd raise that exception. With the table of contents, we have our own ruby file generating its DOM. 

I don't see the equivalent code where I could lint before middleman renders the page.

**Comment by michaelrkn** [comment]
I think you'd need to make your own Middleman plugin to do this. You can reference toc.rb and highlighter.rb, as well as the [documentation](https://middlemanapp.com/advanced/custom_extensions/).

**Comment by mtthgn** [comment]
Just wanted to let everyone know I haven't forgotten about this! I plan on getting some work done on this during the weekend :smiley:

**Comment by michaelrkn** [comment]
Thanks @mtthgn!

**Comment by michaelrkn** [comment]
Hey @mtthgn - any progress on this?

**Comment by michaelrkn** [comment]
I'm adding "help wanted" back to the related issue, but @mtthgn feel free to ping me if you want to take this up again.

**Comment by acorncom** [comment]
This works on #613

**Comment by acorncom** [comment]
I'm going to close this for now, but we're happy to re-open it if folks want to work on it further!

**Pull request closed without merging**
