### PR TITLE
ember-cli rewrite of the Models section

### PR DESCRIPTION
**Pull request by locks**
Ready to merge.

### CODE REVIEW

**Comment by trek** [comment]
Is this mergeable yet or no?

**Comment by locks** [comment]
Not yet, I have questions regarding a section and then a final review.

**Comment by rwjblue** [comment]
Please let us know what you are blocked on, so we can help move it forward.

**Comment by locks** [comment]
@trek mergeable

**Comment by stevekinney** [comment]
I reviewed this and it looks good. :shipit:

**Comment by trek** [comment]
Can you squash this down for us? Thanks.

**Comment by locks** [comment]
@trek :shipit:

**Pull request merged**
