### PR TITLE
[WIP] Remove ObjectController references

### LINKED ISSUE #81: Guides should remove references to Ember.ObjectController
There is at least one known usage in https://github.com/emberjs/guides/blob/master/source/templates/actions.md, but we should scan other files for usage, as well.

Here is some reference documentation, http://emberjs.com/guides/deprecations/#toc_objectcontroller

### PR DESCRIPTION
**Pull request by Serabe**
Try to fix #81

### CODE REVIEW

**Comment by trek** [comment]
Can you rebase and PR against both master and v1.11?

**Comment by trek** [comment]
Looks like this needs a rebase.

**Comment by trek** [comment]
Is this good then?

**Comment by Serabe** [comment]
It should be.

**Pull request merged**
