### PR TITLE
Metadata now lives in 'meta', not 'content.meta'

### PR DESCRIPTION
**Pull request by pablobm**
Hello, Ember newbie here. I might be terribly wrong but, after some trial&error, debugging, and looking at ember-data's code, I believe this is that the guides should actually say.

Please enlighten me if this is not the case :-) Thank you!

### CODE REVIEW

**Comment by trek** [comment]
cc @igorT

**Comment by wecc** [comment]
This is correct, as long as `result` is the result from a `store.query` call.

**Comment by michaelrkn** [comment]
@wecc `result` is the result from a `store.metadataFor` call - is this still correct? Help us figure out whether to merge or close this PR. Thank you! :)

**Comment by wecc** [comment]
`store.metadataFor()` and `store.setMetadataFor()` has been deprecated.

You can get metadata from:

1. The result from a `store.query()` call
2. On a belongsTo relationship
3. On a hasMany relationship

```js
store.query('author', { query: { include: 'books' } }).then((result) => {
  // result.get('meta')
})
```

```js
let user = store.peekRecord('user', 1);
user.get('friends').then((friends) => {
  // friends.get('meta');
});
```

**Comment by michaelrkn** [comment]
Thanks @wecc! @pablobm, can you update this PR to:

* switch `var result = this.store.find` to `var result = this.store.query`; and
* remove this guide's references to `metadataFor`.

Thank you!

**Comment by pablobm** [comment]
@michaelrkn: done. I also:

  1. Incorporated @wecc's comment
  2. Rephrased mentions to serializers to be more generic (not just assume it's all `JSONSerializer`)

**Comment by michaelrkn** [comment]
Awesome! @wecc can you take another look to make sure this all looks good? (It's just a bit beyond my expertise level.)

**Comment by bmac** [comment]
Content looks good to me. :+1:

**Comment by locks** [comment]
@pablobm can you rebase please?

**Comment by pablobm** [comment]
@locks: rebased now

**Comment by locks** [comment]
@rwjblue :shipit:

**Pull request merged**
