### PR TITLE
Ember CLI user guides

### LINKED ISSUE #410: Merge ember-cli.com & emberjs.com guides
We can start moving content over from ember-cli.com with the goal to merge the two documentations into one. I've split up ember-cli.com into "user guides" and "extending" so we can first focus on the "user guides". Below are some first thoughts on a toc

I propose to add a section to the guide, right under "getting started" called "Developing your app"
- Configuration
- Development server
- Managing dependencies
- Building your app

In getting started, we should add:
- Upgrading

Finally, at the very bottom of the guide, I think a "Common issues" section with dedicated sub-sections (eg. for CLI) would make sense.

### PR DESCRIPTION
**Pull request by joostdevries**
Extremely raw copy-paste - let's start tuning this. 
Fixes #410 

Rendered: http://ember-playground.joostdvrs.com/developing-your-app/

### CODE REVIEW

**Comment by michaelrkn** [comment]
Hey @joostdevries! Thanks for spearheading the work to move ember-cli docs into the guides. 

As you may have noticed, the guides have gotten a bit out of control recently, with a lot of sections and content and not a lot of cohesion. A few of us have been talking about how to make things better before merging in a bunch of new content. One thing that everybody agrees on is that since Ember CLI is such an integral part of the recommended happy path, it should be fully integrated into the rest of the guides. 

What I'd really love to see, and I think I'm representing the views of the other folks who have been a part of this discussion (especially @trek and @locks), is to move the content from this PR out of its own section and into the rest of the guides as much as possible. For example, the _Running tests_ page would get moved into the _Testing_ guide, _Mock API Responses_ part could go into the _Models_ section, and commands like `$ ember generate controller` would get moved into the _Controllers_ guide. There are some pieces that aren't totally clear, like where _Building for Production_ goes (one thought is to slim it down and put it in _Getting Started_), but that's the general idea.

Does that sound okay to you?

**Comment by joostdevries** [comment]
@michaelrkn Sounds perfect. I didn't expect this to merge as-is but I needed this input to continue.

Proposals:

- [ ] `configuring-ember` should contain a basic chapter which holds all config basics (ie. "there's a file called config/environment" + some basics). Maybe called "Environments"?
- [ ] The section on mocking can be moved to `models` but probably also needs a link from `testing`
- [ ] Asset management + building/deploying should move to getting started

Open ends:
- `ember-cli-build.js` vs. `config/environment.js` This is tricky to explain and I'd rather delegate everything to the config.
- upgrading

Impact on the CLI docs (cc @stefanpenner):
- Once all of the above is resolved, I'd say we can remove the user guides from ember-cli.com and point to the Ember guides.
- **Remaining chapters + proposals**
  - **Coffeescript, stylus etc.** I'd say that the addon ecosystem will take care of this. If I Google `ember coffeescript` or `ember stylus` I get the right addon straight away. Ecosystem should handle this. 
 - **Common issues**
   - **CSP**. I'd say either remove the addon from the default blueprint or make sure it **never** blocks the user.
    - **NPM trolling** Not sure, maybe put link to relevant article in getting started? Ecosystem should handle this IMO.
    - **Installing from behind proxy** Not an ember issue and [Google is your friend](https://www.google.nl/search?q=fatal%3A+unable+to+connect+to+github.com). Ecosystem should handle this.
    - **Using canary builds** Either mention it on the `builds`page (not the guide) or merge with dep. management.
    - **Removing default libs** NPM basics, not needed in Guide IMO. Ecosystem should handle this. 
    - **Windows issues** I'd make a repo/page specifically for windows users. Too many exceptions to weave them in. Ecosystem should handle this. 
    - **Vagrant** Ecosystem should handle this. 
  - **Editors** Ecosystem should handle this.

**Comment by michaelrkn** [comment]
That all sounds great to me! The easiest way for folks to review and merge this in is if you can make a separate PR for each of the guides changes, eg one PR for the testing stuff, one PR for the mock server, etc. Thanks a bunch!!

**Comment by michaelrkn** [comment]
I'm going to close this in favor of continuing the discussion on #410.

**Pull request closed without merging**
