### PR TITLE
Remove guides.yml entry for already-removed metamorph info

### LINKED ISSUE #154: a 404 error page of  guides
[see this page of understanding ember.js](http://guides.emberjs.com/understanding-ember/keeping-templates-up-to-date)

### PR DESCRIPTION
**Pull request by michaelrkn**
Fixes #154.

### CODE REVIEW

**Comment by trek** [comment]
Can you provide more info on how this address #154? That Issue seems be about @zhengjunwei running across a no-relative link

**Comment by michaelrkn** [comment]
@zhengjunwei noted that http://guides.emberjs.com/understanding-ember/keeping-templates-up-to-date gives a 404. The only like to that page I could find in the docs is from the nav bar. I don't think the issue has anything to do with a non-relative link, unless I missed something.

**Comment by trek** [comment]
http://guides.emberjs.com/understanding-ember/keeping-templates-up-to-date is not a url that would ever show up on the guides site. http://guides.emberjs.com/v1.10.0/understanding-ember/keeping-templates-up-to-date would be the url. It wasn't clear from @zhengjunwei's Issue how he ended up on a page that lacked a revision slug in its url.

**Comment by michaelrkn** [comment]
Oh I see what you're saying. I assumed it was just from copying the relative URL from the dev environment and then prepending guides.emberjs.com.

**Pull request merged**
