### PR TITLE
Formatting fix in 1.13 docs for #each with key

### PR DESCRIPTION
**Pull request by mattmcmanus**
This one should be to the right branch

### CODE REVIEW

**Comment by locks** [comment]
@mattmcmanus We don't really accept PRs to the version branches since we don't currently redeploy them. While 1.13 will be a special case, I'm not sure this helps with out workflow.
@michaelrkn what do we do about this? related: https://github.com/emberjs/guides/pull/545 Should @mattmcmanus make the PR against master instead then we merge it before #545?

Sorry if I'm overcomplicating.

**Comment by michaelrkn** [comment]
If this feature isn't available in 2.0, I don't think we want to encourage people to use it in 1.13.

**Comment by mattmcmanus** [comment]
Wasn't aware of that. Sorry. Just saw an easy fix and jumped on it.

**Comment by michaelrkn** [comment]
@mattmcmanus no worries, thanks for contributing!

**Pull request closed without merging**
