### PR TITLE
updated writing-helper.md

### PR DESCRIPTION
**Pull request by rahulsingh-js**
This is just a suggestion to use ecmascript 6 wisely in code. This will not only make readers familiar with latest ecmascript but also gives better readability experience.

### CODE REVIEW

**Comment by rahulsingh-js** [comment]
Suggestion are welcome.

**Comment by locks** [comment]
While you're editing this file, could you change all the multiline variable declaration to independent declarations, like:

```
let dollars = Math.floor(value / 100),
      cents = value % 100,
      sign = '$';
```

into 

```
let dollars = Math.floor(value / 100);
let cents = value % 100;
let sign = '$';
```

Thank you!

**Comment by rahulsingh-js** [comment]
sure

On 21 June 2016 at 20:19, Ricardo Mendes <notifications@github.com> wrote:

> While you're editing this file, could you change all the multiline
> variable declaration to independent declarations, like:
>
> let dollars = Math.floor(value / 100),
>       cents = value % 100,
>       sign = '$';
>
> into
>
> let dollars = Math.floor(value / 100);
> let cents = value % 100;
> let sign = '$';
>
> Thank you!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/emberjs/guides/pull/1516#issuecomment-227463944>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ARY59PBXltQOYTKS9EcbyibcW1ZAcRGNks5qN_nhgaJpZM4I6zka>
> .
>



-- 
*Thanks & Regards*
_________________________
*Rahul Singh**, **passionate JavaScript Developer **, *
*Gurgaon, India*
Tel: +91-81-30-319862
Skype: contact.rahul1991
contact.rahul1991@gmail.com | github.com/rahulsingh-js/

**Comment by acorncom** [comment]
@rahulsingh-js I like it.  Have you checked to see what these changes look like in our syntax highlighter?  My guess is that we're going to lose syntax highlighting, as CodeRay (our current syntax highlighter) doesn't understand ES6.  We've been wanting to replace it for just that reason ...

**Comment by rahulsingh-js** [comment]
I cross-checked and it looks fine. I guess you can view the preview options and have a look of the page again. 
In case you find any issue somewhere please let me know. I would be very happy to resolve.
Thanks

**Comment by rahulsingh-js** [comment]
Please let me if you disagree on my above statement.

**Comment by locks** [comment]
Thank you!

**Pull request merged**
