### PR TITLE
Update simple-component.md

### PR DESCRIPTION
**Pull request by feipinghuang**
There have no rental-property-type helper in this tutorial.

### CODE REVIEW

**Comment by acorncom** [comment]
Any details on why you want to take that out?

**Comment by feipinghuang** [comment]
@acorncom There have no rental-property-type helper in this tutorial page.

**Comment by toddjordan** [comment]
@feipinghuang  good catch!  thanks for the contribution :-)

**Comment by toddjordan** [comment]
@homu r+

**Pull request merged**
