### PR TITLE
Document preferences on how to link to API methods

### PR DESCRIPTION
**Pull request by acorncom**
A question came up as I was adding links to API pages (https://github.com/emberjs/guides/pull/875) about how we want to link to methods.  @locks suggested I open this PR so we can come up with a standard approach to this.

### CODE REVIEW

**Comment by locks** [comment]
My knee jerk reaction is that I don't like adding the parenthesis that much because it might induce the error that the function doesn't have params.

**Comment by acorncom** [comment]
I'm happy doing either, just think we should have it consistent and documented (I've seen both :-)

**Comment by michaelrkn** [comment]
> it might induce the error that the function doesn't have params

Can you elaborate? I don't understand this problem.

**Comment by locks** [comment]
> Can you elaborate? I don't understand this problem.

That `this.store()` doesn't have any arguments. I know it's silly, but… :P

**Comment by michaelrkn** [comment]
Oh, I see. But it still needs to be called with `()`... I personally don't see this as confusing.

**Comment by acorncom** [comment]
I'd been thinking we would only add the `()` to methods that needed it when you called them (instead of properties).  But I'm fine either direction.  Mainly was interested in clarifying which way we do this, as we've got an interesting mix on the site right now ;-)

**Comment by michaelrkn** [comment]
Right. Only Ruby developers would be confused by invoking an argument-less function with parens ;)

**Comment by acorncom** [comment]
Oh, is that the issue?  I'm not super familiar with Ruby, so that escaped me :-)

**Pull request merged**
