### PR TITLE
Fixed grammatically incorrect sentence in ember-data.md

### PR DESCRIPTION
**Pull request by pizza**
In v2.11.0 and earlier, the sentence I changed used to be `When we open the model file, we see:`, which was correct.
It later was changed to the current `When we open the model file reveals a blank class extending DS.Model:`, which doesn't sound right.

### CODE REVIEW

**Comment by toddjordan** [comment]
Thank you @pizza ! Yeah, good catch.  

We have a pretty big pr coming in today #1818 

could you check if the same grammar issue is there?  If so I'm inclined to wait until it lands to merge.

**Comment by pizza** [comment]
Thanks! I just checked #1818 (a pretty big PR indeed) and the grammar issue in my PR isn't there.

**Comment by pizza** [comment]
@toddjordan I noticed that this PR was closed in #1818, but this typo is still there, in the last version of `ember-data.md` on master.

**Comment by locks** [comment]
Done!

**Comment by pizza** [comment]
Thanks @locks

**Pull request merged**
