### PR TITLE
#1076 break out "Defining Relationships" section

### PR DESCRIPTION
**Pull request by skaterdav85**
@acorncom looks like model relationships are mentioned in those sections so it makes more sense to keep it right after Defining Models

### CODE REVIEW

**Comment by acorncom** [comment]
@locks @michaelrkn you guys ok with this?

**Comment by michaelrkn** [comment]
Would it make sense to combine Working With Relationships into this page and just call it Relationships?

**Comment by skaterdav85** [comment]
The only downside to that is that "Working with Relationships" talks about creating records, updating records, etc, which readers wouldn't have seen yet since "Creating, Updating, and Deleting" follows that.

**Comment by acorncom** [comment]
Fixes #1076

**Comment by michaelrkn** [comment]
What if we moved the new Relationships page after Creating, Updating and Deleting?

**Comment by skaterdav85** [comment]
Creating, Updating, and Deleting mentions relationships :laughing:

**Comment by michaelrkn** [comment]
Hrm, could we pull that info out? It looks like just two little things at the beginning and end.

**Comment by skaterdav85** [comment]
Ya. I think the stuff about relationships in "Creating, Updating and Deleting" would be better suited for "Working with Relationships"

**Comment by acorncom** [comment]
:+1:

**Pull request merged**
