### PR TITLE
[input-helpers] Tweaks header levels

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Comment by mixonic** [comment]
Is there some context to this that motivates the change? I'd be happy to merge stuff like this if there was some information about what is happening.

**Comment by locks** [comment]
@mixonic I believe this is in line with previous edits: https://github.com/emberjs/guides/commit/0c1f977de385619736a29b2e18baa5ce21a53563.

The first header is superfluous regardless of the level, since it gets repeated due to the section name being the same.

**Comment by mixonic** [comment]
Seems good!

**Comment by locks** [comment]
:beers: :smile:

**Pull request merged**
