### PR TITLE
Explain what an outlet is.

### PR DESCRIPTION
**Pull request by sheriffderek**
I'm not sure of the best way to word it, but the outlet should be explained. I pulled this copy from 2.7's guide.

### CODE REVIEW

**Comment by locks** [comment]
I think the explanation would be better placed after https://github.com/emberjs/guides/pull/1728/files#diff-41d19b956479ca7b821c55def80da82bR89. Something like: "When we add routes later on, they will be rendered inside `{{outlet}}`".
What do you think?

**Comment by sheriffderek** [comment]
When you say, ..."better placed after..." I'm not sure where you mean, but anyplace is fine with me. I just don't want it to go unmentioned. I was showing someone the walkthrough and they were thrown off by that.

**Comment by locks** [comment]
> When you say, ..."better placed after..." I'm not sure where you mean, but anyplace is fine with me.

I mean line 89 of the document, after "You should see that the welcome page has been replaced by "PeopleTracker".

**Comment by locks** [comment]
Thank you for your help!

**Pull request merged**
