### PR TITLE
Tutorial tweaks to be in line with the Ember.js style guide

### PR DESCRIPTION
**Pull request by brianarn**
I was going through the Ember.js tutorial this evening, and I have to say that it's a wonderful, wonderful resource. I'm super happy with it. It felt really intuitive and great.

As I went through, I noticed a few small things that were out of line with the [Ember.js style guide](https://github.com/emberjs/ember.js/blob/master/STYLEGUIDE.md), so I figured I would make a small PR that brings in some alignment.

Happy to squash it down as well, I was just committing as I went.

Thank you all for writing a great resource! :)

### CODE REVIEW

**Comment by acorncom** [comment]
@brianarn If you can squash things that'd be great. Glad it's been helpful, it's taken a while to get to that point :-)

**Comment by brianarn** [comment]
I think that's all I've seen in the tutorial for now. If I bump into anything weird/odd otherwise, I'll raise an issue or a PR. :)

Thanks!

**Comment by locks** [comment]
:tada: 
@homu r+

**Comment by brianarn** [comment]
Hm, I thought Travis was passing fine before I squashed. That's kind of odd.

**Comment by brianarn** [comment]
The failures I'm seeing in Travis seem to be unrelated to my PR. If there's something I can do to help that, I'm happy to, I'm just not sure what it'd be. :)

**Comment by locks** [comment]
It's related to our setting up of the localization infrastructure. Hm, we'll have to figure it out.

**Pull request merged**
