### PR TITLE
meta viewport to fix mobile display

### PR DESCRIPTION
**Pull request by nicholalexander**
part 1 of #1036.

i added a media query to style the select box container as it was running up against the header in mobile.

### CODE REVIEW

**Comment by locks** [comment]
Can you squash the commits when the PR is ready?

**Comment by nicholalexander** [comment]
@locks - sorry.  squashed them.  let me know if it looks good.  thanks!

**Comment by michaelrkn** [comment]
Thanks @nicholalexander!

**Comment by acorncom** [comment]
Agreed, :+1:

**Pull request merged**
