### PR TITLE
[WIP] Whitespace/new line clean up

### PR DESCRIPTION
**Pull request by rtablada**
This PR is to make new line and whitespace more consistent across the guides.

There's a few things going on when I decide to add or reposition a line break:

* Line break for every new sentence
* Line break after the last comma in sentences > 120 characters
* Line break after logical statements in sentences > 120 characters with no other punctuation as separation.

This line break strategy will help retain the styleguide outlined in CONTRIBUTING.md as well as provide a better separation of statements which should help with some of the angry git diffs that occur when writing docs and prose.

### CODE REVIEW

**Comment by michaelrkn** [comment]
Wow! Awesome. Thanks @rtablada!

**Comment by rtablada** [comment]
@michaelrkn whoops, I was still working on converting whitespace...

**Comment by rtablada** [comment]
Only got through 1/4 of things this morning.

Also, should the contributing docs give those guidlines as to when to make a new line? I know that it won't be completely enforced, but at least give contributors an idea of when to line break?

**Comment by michaelrkn** [comment]
Oops, crap, I missed the WIP. Anyways, just open a new PR.

Check out #1053.

**Pull request merged**
