### PR TITLE
Setup a 404 page

### PR DESCRIPTION
**Pull request by filipecrosk**
Addresses issue #1285 

Since the firebase's docs say to create a 404.html on the root, I created this page on the root of our project. Let me know if the right place.

### CODE REVIEW

**Comment by acorncom** [comment]
c0e14a84-e1e8-11e5-9a26-d3e3e1c541eb

@filipecrosk Could you add a bit more vertical space between the Tomster and the header below on the mobile page?  Maybe a 1em space or so ...

Other than that, I like what I see! :+1:

**Comment by filipecrosk** [comment]
@acorncom done! =)
screenshot 2016-03-04 09 30 47

**Comment by acorncom** [comment]
@filipecrosk Nice :-)  So we're waiting to get an updated Tomster image from @wifelette and then we'll want all the commits squashed down to one commit.  At which point, let's get this merged! :+1:

**Comment by wifelette** [comment]
ember-fishy_r01

Updated Tomster attached!

**Comment by filipecrosk** [comment]
@acorncom commits squashed :)

**Comment by locks** [comment]
@filipecrosk hhmm, I believe that's fine.

**Comment by locks** [comment]
@homu r+

**Pull request merged**
