### PR TITLE
Update Ember.LinkView -> Ember.LinkComponent

### PR DESCRIPTION
**Pull request by truenorth**
Related: https://github.com/emberjs/ember.js/pull/11594

### CODE REVIEW

**Comment by rwjblue** [comment]
I would prefer to suggest folks export their own link-to component vs reopening like this.

**Comment by tomdale** [comment]
I agree with @rwjblue: we should have folks subclass rather than reopen the framework class. Is that what you had in mind?

**Comment by truenorth** [comment]
Seems like a lot of work (a lot of code changes within an app) just to add a new attribute binding to some/all links, relative to reopening.

Can either of you guys provide me with an example of how this could be easy? I'm thinking of how you could retrofit many/all of a large app's `{{link-to}}`s with a `{{my-link-component}}`, such that it's a mechanical refactoring. 

It would seem that you'd have to build a new handlebars helper in order to continue using the same positional args

**Comment by rwjblue** [comment]
The following should do it for 1.13+:

    // app/components/-link-to.js

    export default Ember.LinkComponent.extend();

**Comment by truenorth** [comment]
awesome. That is quite simple. I'll add it to the guides

**Comment by rwjblue** [comment]
Heh, make sure it works first :smiley:

**Comment by mixonic** [comment]
@rwjblue fwiw I'm unsure I agree. `-link-to` is clearly meant to be private, and `reopen` is a public documented API. I understand the elegance in using a `-link-to` component name, but we should make it `link-to` or something if it is a publicly supported strategy.

**Comment by truenorth** [comment]
One additional question -- how would one do this using globals instead of ES6?

**Comment by michaelrkn** [comment]
I believe we're not discussing globals in the guides anymore. 

@truenorth @mixonic @rwjblue what's the way forward here?

**Comment by tomdale** [comment]
All discussion of globals should be extracted to a transition guide that explains the legacy globals mode, and explains the rules for mapping from module examples to globals.

**Comment by locks** [comment]
Thanks @truenorth. Some of the concerns raised will be addressed in the ongoing review for 2.0.

**Pull request merged**
