### PR TITLE
Remove global `App` variable

### PR DESCRIPTION
**Pull request by swashcap**
The `App` variable, previously used as the Ember application's global namespace, is no longer used in the guides in favor of ES6 modules. The `App` would be undefined in this case.

### CODE REVIEW

**Comment by rwjblue** [comment]
Hmm, looks like this PR is pulling in all commits from master to v1.11.

We just need the specific change from  fe1037c.

**Comment by swashcap** [comment]
> Hmm, looks like this PR is pulling in all commits from master to v1.11.

Ah, shoot. How do I pick just that one commit? `cherry-pick` locally and do another PR?

**Comment by rwjblue** [comment]
Yeah, I think that is easiest.  You could also likely use the github online file editor and just make the change there too.

**Comment by swashcap** [comment]
See #176.

**Pull request closed without merging**
