### PR TITLE
Object inspector guide review

### PR DESCRIPTION
**Pull request by mattw59**
Addresses part of #602

### CODE REVIEW

**Comment by michaelrkn** [comment]
Looks great to me! I'd like to get another set of eyes from somebody who's more familiar with the Inspector.

**Comment by mattw59** [comment]
Sounds good, I'll keep plugging away on the rest of this section.

**Comment by locks** [comment]
Can you squash?

**Comment by mattw59** [comment]
Yeah, I'll get this and the others squashed over lunch today

**Comment by mattw59** [comment]
Sorry about this goofiness with commits and such. I managed to **really** hose up my fork, so I ended up deleting it. This and two other small PRs are combined into one new, small PR with a single commit from a new fork, as noted in #718 above. Again: apologies for the goofiness.

**Pull request closed without merging**
