### PR TITLE
{WIP} Implements highlighting

### LINKED ISSUE #77: Update Code Blocks to include additions, removals, and highlights
A big challenge in writing tutorials where code mutates over time is accurately drawing the reader's attention to lines of code that have been added, removed, or need highlighting.

The react docs do an excellent job here:
getting started react 2015-03-22 10-52-51

They've augments the fenced code 'metadata' section with a micro syntax to define highlights:

Highlight one line:
~~~
```javascript{10}
~~~

Highlight multiple lines:
~~~
```javascript{3,10,55}
~~~

In addition to this, we can expand the syntax to include classes for line additions and removals:

Line 10 is removed:
~~~
```javascript{-10}
~~~

Line 10 is added:
~~~
```javascript{+10}
~~~

Line 10 is removed, line 15 is added, line 16 is highlighted:
~~~
```javascript{-10,+15,16}
~~~

### PR DESCRIPTION
**Pull request by danmcclain**
**WIP** DO NOT MERGE

At the end of the filename or language add `{1,2,-4,+5}`,
`+` signifies that the line should be marked as added
`-` signifies that the line should be marked as removed
line numbers are otherwise highlighted

Does not currently handle ranges

Also updates colors in code blocks, fixing contrast

Closes #77

### CODE REVIEW

**Comment by trek** [comment]
I'm :-1:  on re-parsing the HTML with Nokogiri after generation. A quick check shows CodeRay already has [a way to highlight lines](https://github.com/rubychan/coderay/blob/master/lib/coderay/encoders/html.rb#L82-L83)

I'm OK to merge this if you can commit to investigating a better way to handle this sometime this week:

Possible solutions are one or more of:

- [ ] see if CodeRay highlighting already supports what we need
- [ ] fork CodeRay and add this, open a PR on CodeRay referencing this issue, open a PR here pointing at your fork
- [ ]  figuring out how to write and use a custom encoder for CodeRay

**Comment by danmcclain** [comment]
@trek Makes sense. Let me investigate a little bit later today.

One thing to note: this repo already is using a Coderay fork: https://github.com/emberjs/guides/blob/master/Gemfile#L7

**Comment by danmcclain** [comment]
Will likely implement this as a custom encoder, using the HTML encoder as a base. Will report later how that is going

**Comment by trek** [comment]
> One thing to note: this repo already is using a Coderay fork:

Can you also follow up on that? I'm assuming this is just because we needed to add a language to mainline CodeRay and never changed back.

**Comment by danmcclain** [comment]
@trek Coderay lacks handlebars (@dgeb's [PR](https://github.com/rubychan/coderay/pull/103) support. If I use mainline:
ember js - templates the application template 2015-03-24 11-18-31

**Comment by trek** [comment]
cc @dgeb: we really need to get that back to mainline.

**Comment by trek** [comment]
> Will report later how that is going

Is this later enough? :D

**Comment by danmcclain** [comment]
@trek Been sidetracked with an Ember-IE8 breakage. I should have some time this weekend to wrap this up. I have started a custom encoder, should be fine to implement what I need to make this happen. Sorry about the delay

**Comment by trek** [comment]
OK. going to merge this now, trust that you'll circle back with a smoother solution.

**Comment by trek** [comment]
Actually, belay that. Let's just wait until it's all done.

**Pull request merged**
