### PR TITLE
Update repositories.md

### PR DESCRIPTION
**Pull request by kentaro0919**
fix 
**Ember Data** - A data persistence library for Ember.js.
to
**Ember Data** - A data persistence library for Ember.

### CODE REVIEW

**Comment by locks** [comment]
@kentaro0919 I'll keep this open in case you find more of them to fix, if that's ok with you.

**Comment by rwjblue** [comment]
`packages/metamorph` is gone

**Comment by rwjblue** [comment]
We should also list tildeio/glimmer, tildeio/htmlbars, https://github.com/krisselden/dag-map, maybe others?

**Comment by kentaro0919** [comment]
@locks It is fine by me. I will add them if I find

**Comment by locks** [comment]
@homu r+

**Pull request merged**
