### PR TITLE
Add HTML Proofer

### LINKED ISSUE #598: Test guides for dead links
We often find that guides end up with dead links as a result of reorganizing content. It would great to have something that would raise an exception if Middleman tries to serve or build a page with a dead link - serve so that you catch it in development if you're working on that page, build so that it gets caught by Travis making sure it builds if you delete a page that somewhere else links to.

### PR DESCRIPTION
**Pull request by bmichelsen**
The HTML Proofer is a gem that validates HTML output. It checks for lots of things, for example whether image references are correct, and that images have alt tags. The main reason we're looking into it, is because it checks for dead links, which is great after reorganizing content.

Have a look at the discussion over at #598, as well as the [html-proofer options](https://github.com/gjtorikian/html-proofer#configuration).

There are still a few issues remaining, which I'm hoping to get feedback on:

- What other options should be enabled? I'm thinking ```check_html``` might be good, unless it's completely out of scope.
- The PR in its current form should have Travis complaining about dead links. However, the ```middleman server``` command still needs work.

Fixes #598.

### CODE REVIEW

**Comment by michaelrkn** [comment]
This is fantastic! And so awesome (or maybe not awesome) to see Travis failing the PR because this has already found dead links. 

Re: other options, `check_html` sounds nice, but at the end of the day, most of the HTML gets generated from Markdown, so hopefully it's all nice and clean. Try enabling it yourself and see if you get a bunch of noise or if it's useful. No other options jump out at me, but if there's anything else you'd like to discuss, let's do so here.

Re: `middleman server`, can you try using:

```ruby
configure :development do
  activate :html_proofer
end
```

and see if this causes exceptions using the development server?

Finally, can you squash your commits, and then also add a commit to fix the problems HTML Proofer has identified, so that Travis is green again?

Thank you for your great work!

**Comment by michaelrkn** [comment]
Hey @bmichelsen - any progress on this?

**Comment by bmichelsen** [comment]
The following errors have been identified by the HTML Proofer:

```
- ./build/applications/initializers/index.html
  *  internally linking to ./dependency-injection, which does not exist (line 87)
```

```
- ./build/configuring-ember/embedding-applications/index.html
  *  internally linking to ../../routing/specifying-the-location-api, which does not exist (line 114)
  *  internally linking to ../../templates/the-application-template, which does not exist (line 88)
```

```
- ./build/ember-inspector/troubleshooting/index.html
  *  linking to internal hash #toc_using-the-inspector-with-jsbin that does not exist (line 99)
```

```
- ./build/models/customizing-adapters/index.html
  *  internally linking to /api/classes/Ember.ComputedProperty.html#method_volatile, which does not exist (line 382)
  *  trying to find hash of /api/classes/Ember.ComputedProperty.html#method_volatile, but /Users/bjorn/Source/Projects/emberjs-guides/build/api/classes/Ember.ComputedProperty.html does not exist (line 382)
```

```
- ./build/testing/unit-testing-basics/index.html
  *  internally linking to ../unit-test-helpers, which does not exist (line 157)
```

With one exception (the first one referring to line 87), I have a hard time figuring out where these URLs should link to. Are you able to help out? I'm happy to have a discussion on chat in order to have this fixed, just let me know.

Also, links pointing to ```/api``` are failing as well, but they are correct (at least in this case). Should we ignore ```/api``` links or is there a better way to deal with them?

**Comment by bmichelsen** [comment]
I'd like to skip the ```check_html```option due to scope since the HTML is automatically being generated by Markdown.

I've been doing some thinking about running the HTML Proofer in development mode, with the hopes of it causing exceptions using the development server. Before I look more into it, I'd like to express a concern with regards to development speed. If we activate the Proofer during development, then every time the file is saved, the Proofer will run. For me, that resulted in a 2 seconds delay which I find unacceptable. I'm sure there are ways we can optimize this, but I'm not too sure it's the way forward.

Any thoughts? :-)

**Comment by michaelrkn** [comment]
Thanks for the update! I've opened #965 to fix the broken links. 

Skipping `check_html` is fine with me. There is the chance that somebody writes borked HTML in their Markdown, but let's cross that bridge when we come to it.

I agree about not slowing down development speed. If we just have the Proofer check for internal links in development mode, and only external links in CI (or not at all), would that make the speed more acceptable?

**Comment by bmichelsen** [comment]
Hm, the Proofer is only checking internal links at the moment so that won't speed things up unfortunately.

**Comment by michaelrkn** [comment]
I just worry that if we don't have this in development, we'll get a lot of PRs where people didn't realize the build was failing, and we'll have to do the whole back-and-forth thing. @locks do you have any thoughts? 

I'm trying to configure this to run in dev so I can get a sense of the slowdown, but I'm having trouble figuring out how to configure it properly. @bmichelsen can you point me in the right direction?

**Comment by michaelrkn** [comment]
@bmichelsen - just want to ping you on getting some help setting this up in development. Thanks!

**Comment by bmichelsen** [comment]
In order to get a sense of how the Proofer affects development, please do the following:

1. Download [a.patch.txt](https://github.com/emberjs/guides/files/43862/a.patch.txt)
2. Inside the project, run ```git checkout -b proofer-takes-forever```
3. Then ```git apply a.patch.txt``` within the newly created branch
4. Run ```middleman server```
5. Go to ```http://localhost:4567/routing/rendering-a-template/index.html```
6. Reload the page

When you're done experimenting, do a ```git checkout .``` to restore the working directory.

**Comment by bmichelsen** [comment]
I think this gets us closer to the goal, but I also see your point about avoiding the back-and-forth. What if we update the documentation on how to contribute, merge the changes and see if it becomes a hassle? If it does, we'll simply revert it and know for sure that it's the wrong approach. :-)

**Comment by michaelrkn** [comment]
Boom! Merged :) Thanks @bmichelsen! In case we do want to enable this in development in the future, do you have any pointers on how it might work to have it more generically check every page as it's built? (Just in case you're not around to work on it more at that point.)

**Pull request merged**
