### PR TITLE
updated the screenshot with the passing navigation tests to be more c…

### PR DESCRIPTION
**Pull request by jaschwar**
…omplete -- showing passing and failed tests

### CODE REVIEW

**Comment by toddjordan** [comment]
The text on the new image is considerably smaller, making the new image harder to read (at least on my macbook display). If you reduce the size of the window, or increase the font size, you should get a better shot.

**Comment by jaschwar** [comment]
I updated with a bigger screenshot let me know if works ? @toddjordan

**Comment by toddjordan** [comment]
Hi @jaschwar the size is 👌  now.  Sorry to be a PITA, but I need to to take another screenshot of the same, except this time uncheck "Hide Passed Tests".  We want to show the user the test that _should be_ passing as well.

**Comment by toddjordan** [comment]
also, like I mentioned in your other PR I prefer larger font relative to window size, so the reader can read it.  Sorry I didn't communicate that better 😦

**Pull request closed without merging**
