### PR TITLE
Change search provider to DocSearch

### PR DESCRIPTION
**Pull request by jeradg**
This PR changes the Guides search provider from Swiftkey to DocSearch.

See issues https://github.com/emberjs/guides/issues/1184 and https://github.com/emberjs/guides/issues/1183 for discussion.

Functionality checked in Chrome and Firefox latest.

### Screenshots

*Small width:*
docsearch-small-width

*Large width:*
docsearch-large

*Typo correction:*
docsearch-spellcheck

### CODE REVIEW

**Comment by jeradg** [comment]
Investigating the failing build. The CSS compiled fine locally. I'll see if a tweak will get it working.

**Comment by jeradg** [comment]
That should do it...

**Comment by acorncom** [comment]
Thanks for doing this.  Ran into a few snags testing it on my end, aiming to do that later this week.

**Comment by trek** [comment]
:+1: nice!

**Comment by acorncom** [comment]
@jeradg Just checked over it, nice work!  Could you squash your commits here and we'll get this merged :-)

**Comment by jeradg** [comment]
Thanks all!

@acorncom: Squashed and good to go.

**Comment by acorncom** [comment]
@homu r+

**Pull request merged**
