### PR TITLE
Fix inconsistency between guide and server output

### PR DESCRIPTION
**Pull request by sotojuan**
The example says the default server displays "Welcome to Ember.js" but actually it's "Welcome to Ember". Just a little inconsistency that was bugging me!

### CODE REVIEW

**Comment by acorncom** [comment]
@sotojuan Thanks, was going to merge this but the Travis test failed. I think it's probably a Travis problem, could you re-run the test? Thanks!

**Comment by sotojuan** [comment]
Sure, but I am not entirely sure how to do that! I don't see a button on Travis to re-run the test.

**Comment by acorncom** [comment]
@sotojuan You'll need to change your commit in some way so that Travis notices that it's a new commit and re-runs. Probably the easiest way would be to rebase against `master`, as there have been new changes which would change your Git commit sha.  Let me know if you need help with that.

**Comment by sotojuan** [comment]
Looks like it worked (amended the commit with no change!).

**Comment by acorncom** [comment]
@homu r+

**Comment by acorncom** [comment]
Thanks!

**Pull request merged**
