### PR TITLE
Change API links to absolute URLs

### PR DESCRIPTION
**Pull request by jagthedrummer**
This fixes issue #44

### CODE REVIEW

**Comment by jagthedrummer** [comment]
Woops, looks like @djbender just beat me to the wire with a similar PR. https://github.com/emberjs/guides/pull/46

**Comment by djbender** [comment]
lol <3

**Comment by djbender** [comment]
ignore my #46. this one is better :)

**Comment by trek** [comment]
Sounds good. Can you open another one that cherry picks this commit into the v10.0.0 branch as well?

**Comment by jagthedrummer** [comment]
Yessiree!

**Comment by trek** [comment]
Thanks for hoping on this so quickly.

**Comment by jagthedrummer** [comment]
No problem! I've been itching to make some contribs since EmberConf and was having trouble finding a place to start. Glad to get going!

**Comment by jagthedrummer** [comment]
@trek The follow up PR you requested : https://github.com/emberjs/guides/pull/48

**Pull request merged**
