### PR TITLE
Improved nav and table of contents on small screens

### PR DESCRIPTION
**Pull request by steveszc**
Reference Issue #1036 
- Added nav element, wai-aria roles, and aria-labels as appropriate to nav and table of contents
- Added collapsable table of contents on small screens
- Added condensed nav menu on small screens

Screenshot of new version:
new-guides

Screenshot of current version: 
old-guides

### CODE REVIEW

**Comment by rtablada** [comment]
@steveszc could you give an example of the top nav being 2 wide instead of 3 up? The spacing looks a bit tight for smaller devices (iPhone 4 and such).

**Comment by steveszc** [comment]
Here's a variation with 2 wide instead of 3 wide on the nav.
Personally I prefer 3w x 2h. The original screengrab for 3w x 2h was a 320px wide viewport, which is about as narrow as you can get on smart phones these days. 

2up-menu

**Comment by locks** [comment]
I prefer the compactness of the three-wide version.

**Comment by michaelrkn** [comment]
I prefer 3 wide too.

**Comment by locks** [comment]
Time to call @homu r+

**Comment by acorncom** [comment]
:+1: Thanks @steveszc

**Pull request merged**
