### PR TITLE
Improve explanation of Ember.run.backburner.DEBUG.

### PR DESCRIPTION
**Pull request by chriskrycho**
Resolves https://github.com/emberjs/ember.js/issues/13074.

### CODE REVIEW

**Comment by pixelhandler** [comment]
Not sure why the build fails, `An error occurred while installing middleman-spellcheck (0.8.0), and Bundler` seems to be an issue, I tried restarting on travis but no dice right now :(

**Comment by acorncom** [comment]
Just restarted the build here, I'm 👍 on merging this with merge errors if the build keeps failing.

Thanks @chriskrycho !

**Comment by chriskrycho** [comment]
I *know* I didn't break that thing. 😝

**Comment by locks** [comment]
@chriskrycho don't get cocky or the spellchecker will get you 👿

**Comment by acorncom** [comment]
Merging here anyway, thanks Chris

**Pull request merged**
