### PR TITLE
Move paragraph from Ember-CLI to Getting Started

### PR DESCRIPTION
**Pull request by toobulkeh**
To highlight the fact that Ember may not be currently up to date

Fixes https://github.com/emberjs/guides/issues/1125

### CODE REVIEW

**Comment by michaelrkn** [comment]
Good idea. I'd prefer that you simply link to the [existing section on upgrading](https://guides.emberjs.com/v2.2.0/getting-started/ember-cli/#toc_upgrading-ember), so that we keep things DRY.

Also, I think we should add a note to the [beginning of the tutorial](https://guides.emberjs.com/v2.2.0/tutorial/routes-and-templates/) after it says "Let's make sure we have a fresh Ember CLI app..." that also points to the upgrading section.

**Comment by toobulkeh** [comment]
Both sound reasonable. I looked for a call-out design in the current guides but didn't find a decent one, which is why I copy/pasted, as the header was large enough to catch the eye while skimming. Is there a callout / alert format that I missed? I also considered a partial, but that would just keep the backend dry - not the text.

I know some technical writers don't like using call outs, so I didn't want to suggest new inserts that weren't wanted.

**Comment by michaelrkn** [comment]
No, there are no call-outs. I think just put it in the text.

**Comment by acorncom** [comment]
@toobulkeh Thanks for pointing this out.  We're going to adjust this slightly in our latest revisions prior to refreshing Ember 2.2 docs, so will close this now.

**Pull request closed without merging**
