### PR TITLE
Stay on same page when switching versions

### PR DESCRIPTION
**Pull request by michaelrkn**
Also updated 404 to be more helpful in case page doesn't exist in the version switched to.

To test the JS code, I went to http://guides.emberjs.com/v1.11.0/concepts/core-concepts/, ran the relevant code:

```js
var versionSelectBox = $(".version-select");
versionSelectBox.on('change', function() {
  var version = this.value;
  window.location = window.location.href.replace(currentRevision, version);
});
```

and then manually switched from v11 to v10.

### CODE REVIEW

**Comment by michaelrkn** [comment]
Closes #206.

**Comment by rwjblue** [comment]
What happens if the guide page you were on in an older version, does not exist in a newer one?

**Comment by michaelrkn** [comment]
You'll get the 404 page, which I updated to be a bit more helpful:

```
This page doesn't exist in this version of the Guides.
Try hitting the back button to go back to where you were,
or go to the <a href="/">Guides homepage</a>.
If you expected something else to be here, please
<a href="https://github.com/emberjs/website/issues">file a ticket</a>.
```

I'm open to other ideas, but this seemed like the most straightforward way to handle it.

**Comment by rwjblue** [comment]
Going to the root of the new version (`/v1.xx.0/`) seems better (vs 404 page) when the specific URL doesn't work.  if we can do it of course...

**Comment by michaelrkn** [comment]
I agree that would be the ideal approach. However, there are trade-offs...

The simplest thing development-wise is to handle the logic client-side, like this:

```
var versionSelectBox = $(".version-select");
versionSelectBox.on('change', function() {
  var version = this.value;
  var newUrl = window.location.href.replace(currentRevision, version);
  
  var exists = $.ajax({type: 'HEAD', url: newUrl});
  
  if (exists === 200) {
    window.location = newUrl;
  } else {
    window.location.href.split(currentRevision)[0] + version;
  }
});
```

However, that adds in the extra HEAD request before making the request for the actual page, which is a bit inefficient.

The alternative is to go server-side. I assume we'd still want to display a 404 for "regular" invalid requests, so that users don't get confused if they try to go to a non-existent URL that they believe should exist and end up on the version root instead. So, we'd need to add something to the request indicate when a request comes from switching versions. Then we'd need to build a Middleman extension to redirect if the page doesn't exist.

What do you think?

**Comment by wagenet** [comment]
Would there be a big issue with doing a pre-emptive HEAD request? In most cases the user won't change the dropdown immediately. We could also display a warning somewhere that they're looking at an old version.

**Comment by wagenet** [comment]
I also wonder if there's a way to improve the SEO for this too. Right now whenever I Google I just get v1.10 stuff.

**Comment by michaelrkn** [comment]
Pre-emptive requests: We'd have to make several requests, one for each
version. We'd also need to handle what happens if a user tries to change
versions before all of the HEAD requests finish. We gain with front-loading
the requests, but we lose with having to make lots of requests and
introducing more code complexity. For people on slow connections, I'm not
sure they'd actually gain anything. What do you think?

Warning for old version: Great idea. Can you open an issue for it?

SEO: Also worth opening an issue for.

**Comment by trek** [comment]
Looks good! Thanks.

**Pull request merged**
