### PR TITLE
Fix broken link to dependency injection guide

### PR DESCRIPTION
**Pull request by MaximAbramchuck**
While info about Dependency Injection in new Ember > 2.0 is not ready yet, I think that we need to route users to the oldest one just to understand concepts.

### CODE REVIEW

**Comment by michaelrkn** [comment]
@locks how is the DI guide coming along?

**Comment by michaelrkn** [comment]
#729 brings back the info, but I don't know if there's a good way to link to it from here. Since controllers are going away shortly, I would say either find a good place to link to once #729 gets merged, or delete this paragraph entirely.

**Comment by MaximAbramchuck** [comment]
@michaelrkn yea, we can wait while #729, but it will be not so soon, so let's redirect user's to old guide for now. it is better than 404.

**Comment by michaelrkn** [comment]
It doesn't matter if we change it here, because it won't get updated until the guides are de-deployed, and they won't be re-deployed before #729 is merged.

**Comment by michaelrkn** [comment]
Oh, this is on an outdated branch, which we be replaced by master shortly.

**Pull request closed without merging**
