### PR TITLE
Ember Core Concepts (image redesign)

### PR DESCRIPTION
**Pull request by alexG53090**
@michaelrkn and I made an information graphic for the "Ember Core Concepts" section of the website. It is a redesign of the the image below, which illustrates the core concepts of ember. 
http://development.ember-guides.divshot.io/tutorial-v2.2.0/getting-started/core-concepts/

Please click on the following links to download the img files. The images are large and will need to be scaled down for production. I am happy to do so, too. Let me know if there are any other edits that need to be made to finalize!

https://s3-us-west-2.amazonaws.com/ember-core-concepts/ember-core-concepts-master.png
https://s3-us-west-2.amazonaws.com/ember-core-concepts/ember-core-concepts-master.jpg
https://s3-us-west-2.amazonaws.com/ember-core-concepts/ember-core-concepts-master.gif
https://s3-us-west-2.amazonaws.com/ember-core-concepts/ember-core-concepts-master.ai
https://s3-us-west-2.amazonaws.com/ember-core-concepts/ember-core-concepts-master.svg

### CODE REVIEW

**Comment by michaelrkn** [comment]
Hey @alexG53090! It looks like you did this work on the redesign branch and are trying to merge into master. Can you move your work to the tutorial branch and open your PR against that branch? Thanks!

**Comment by alexG53090** [comment]
Hey! I opened a PR in tutorial against redesign is that right? Thanks!

**Comment by michaelrkn** [comment]
Closer! Open a PR in tutorial against tutorial.

**Comment by alexG53090** [comment]
ohh, haha. OK, hopefully third time's the charm :)

**Comment by michaelrkn** [comment]
Ha, not quite :) Are you on the Ember Slack (https://embercommunity.slack.com/)? Ping me (@michaelrkn) and I can walk you through how to do this properly.

**Comment by alexG53090** [comment]
closed in favor of #987

**Pull request closed without merging**
