### PR TITLE
Fixing Test JSBins

### PR DESCRIPTION
**Pull request by ryanmurakami**
Fixed ember-qunit script tags for jsbins.

### CODE REVIEW

**Comment by trek** [comment]
@Serabe how did these survive the JSBin removal?

**Comment by Serabe** [comment]
@trek somehow, the merge of my PR is not in the v1.10.0 branch. No jsbin survived but I cannot find your merge 07a806779c889291bccc75e85d61644d2e1e089f in [v1.10.0 commits](https://github.com/emberjs/guides/commits/v1.10.0).

Maybe it was branched with the contents before the ember-cli update?

**Comment by trek** [comment]
Ooooh, I see @ryanmurakami targeted v1.10.0.

**Comment by ryanmurakami** [comment]
@trek Are we good? I noticed the jsbins were still broken in the 1.10 version in the guides, which is why I pushed this.

**Comment by trek** [comment]
@ryanmurakami we're fine. All JSbins are broken in 1.10 (they broke as an external dep). We just chose not to fix them and simply remove them on master, which became 1.11

**Pull request merged**
