### PR TITLE
updated the screenshot to be consistent with the guide, has gotten ou…

### PR DESCRIPTION
**Pull request by jaschwar**
…t of date

### CODE REVIEW

**Comment by locks** [comment]
It's a bit smaller than the original, do you have a way to test visually on a retina screen?

**Comment by toddjordan** [comment]
The font turns out a bit small to read.  Could you retake the screen shot with a narrower window?  The image's width is capped to the width of the screen, so I think a narrower window will show the image bigger. Here's what it looks like today.  I'd like the get the text size closer to the tutorial text size.

image

**Comment by toddjordan** [comment]
Will address #1665 when merged

**Comment by jaschwar** [comment]
I updated with a large screenshot, let me know what you think ?

**Comment by toddjordan** [comment]
not quite.  😬   I was talking about less the pixel size of the image, but rather the size of the font within the image.  The images get resized to fit the screen, so what I'm looking for is a smaller window size, so that the font shows bigger.  either that or a bigger font size.

**Comment by acorncom** [comment]
@jaschwar Any updates here?  Would love to get this merged ...

**Pull request closed without merging**
