### PR TITLE
Removes Cookbook

### PR DESCRIPTION
**Pull request by locks**
I am in the process of potentially finding them a new home.
We can link to said home when it is established.

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

**Comment by eccegordo** [comment]
Does it make sense to build in some way to collect curated cookbooks from the community and publish in a process independent of the guides?

When I was first starting out learning ember a simple code example list like what Eric Berry @cavneb published was very useful

http://coderberry.me/blog/2013/08/07/useful-ember-code-examples/

There are lots of this stuff around the web so having some way to bubble up to ember website the best of the best would be very helpful for people just starting out and trying to learn from code examples.

At least two problems though:

1.) A huge index of cookbooks can become a beast to maintain and there is not enough bandwidth on the core team. @trek suggested as much when we talked about this at ember conf 2014

2.) The community cookbooks themselves could vary in quality.

I guess I am asking for something between random blog post and  cookbook perfectly crafted by core team.

I want moar cookbooks but with some minimal curation. Hell, even some way to register the JSBin or Ember Twiddle examples that get created. 

Some mechanism that catalogs this stuff and improves their discoverability would be invaluable.

Maybe even a blind nomination and voting process where important examples organically bubble up and get archived into the ember js website. 

Not asking the core team to maintain them, just provide some mechanism to showcase examples the community deem valuable, and perhaps were reviewed at some level by the core team for gross inaccuracies.

Maybe it is as simple as some official github forks of projects that live under the ember organization.

**Comment by locks** [comment]
@eccegordo we definitely to not have the bandwidth to sustain a Cookbook, hence why it's getting punted to the community. It has done a great job of supplanting the guides with blog posts and the like, so I'm sure that if there is a hub for this that the community will handle it.

I have tentatively moved the Cookbook to an EmberWatch fork to see if it fits. I expect the workflow to be something like: you'd submit a PR with your cookbook (a markdown file), the community would review it and publish it. You can also contribute to https://emberflare.com/, which isn't as curated.

**Comment by locks** [comment]
Which isn't to say that core is completely detached from it. A certain level of quality is expected and for that to happen core needs to be involved so the right message is passed on.

**Comment by locks** [comment]
P.S. Cookbooks are a pain for every project xD I was involved with Sinatra for a while and the cookbook was one of the more popular topics.

**Comment by eccegordo** [comment]
@locks totally understand. As I think about this more carefully what seems important is having a convenient to use compendium of examples, especially ones that communicate change in API.

A great example is the ember select in the deprecations guide.
http://emberjs.com/deprecations/v1.x/#toc_ember-select

I am hoping as the docs release process improves that this stuff becomes prevalent. Obviously one can find good code examples in the API docs. But as releases come out a lot of people are just busy and want to zero in on what is new. And these code samples go a long way to addressing that need.

**Comment by locks** [comment]
https://github.com/emberwatch/emberwatch/pull/40

**Comment by pixelhandler** [comment]
@locks @rwjblue Can someone provide any analytics info regarding which cookbook pages were viewed most, or any other analytics data what would show what was successful from the cookbooks effort? (now removed and abandoned by core team) It would be nice for those who continue the tutorial documentation (aside from the website/guides) to know what cookbook content was successful and what was not. Perhaps there is something to be said by the analytics that can help guide the future effort.

**Comment by mixonic** [comment]
@pixelhandler I'm pretty sure we can share that, but unsure who has access. We will dig it up, if we forget please ping in the documentation chat.

**Comment by trek** [comment]
> (now removed and abandoned by core team)

These were not abandoned. They were handed off to the community members who were interested in working on them.

**Comment by Frozenfire92** [comment]
Is there a new definitive home for the cookbook? Just when I came up with something perfect for it I go to see they are gone in 2.0 :astonished: 

Will [this](https://github.com/emberwatch/emberwatch/pull/40) be the new home?

**Comment by mixonic** [comment]
@Frozenfire92 yes, that is the intent.

There is a tradeoff we need to strike in quality and quantity. Keeping up with the current guides is already very difficult to do, and we need to focus on what we can do well to ensure new developers succeed. The number of topics cookbooks could cover is basically infinite, and they were already falling behind without that many published.

I'm hopeful they can find a good home outside the main guides.

**Comment by locks** [comment]
@Frozenfire92 there is a larger community effort being organized for a revised Cookbook, you can connect with them in the Slack community.

**Pull request merged**
