### PR TITLE
Added Bower section to Installing Ember -> Dependencies

### PR DESCRIPTION
**Pull request by jderr-mx**
Addresses #1513 adds documentation to install Bower as an Ember dependency after npm and Git

### CODE REVIEW

**Comment by tomdale** [comment]
Looks good to me. @emberjs/learning-team-managers, WDYT?

**Comment by jderr-mx** [comment]
Added a screenshot of the built guide page.

guides

**Comment by tomdale** [comment]
😍

**Comment by locks** [comment]
I'd put it after npm just to keep "package managers" together. And I thought you didn't really need the global bower, at least for starting a project.

**Comment by rwjblue** [comment]
@locks - You do not need it for a new project, but I thought this was talking about upgrading (and it told you to run bower install).

**Comment by locks** [comment]
🤔 the court will allow it 💥 🔨 .
@jderr-mx I changed my mind, can you put `Git` at the top of Dependencies? That way all of the JavaScript thing is in a row. Much obliged :)

**Comment by jderr-mx** [comment]
Updated the PR here is a screen shot of the built page.

screenshot from 2016-06-30 17-40-59

**Comment by jderr-mx** [comment]
The Travis Build failed on : `misspell  The word 'DependenciesGit' is misspelled`

This appears to be a false positive. I looked at the generated html source for getting-started/index.html which is:

`<h2 class='anchorable-toc' id='toc_dependencies'>Dependencies.</h2><h3 class='anchorable-toc' id='toc_git'>Git</h3>`

It looks like middleman spellcheck is ignoring the h2 and h3 tags and because there are no line breaks between them in the html source, it interprets it as the word `DependeciesGit` 

I added it to spelling-exceptions.txt which allowed it to pass.

**Comment by locks** [comment]
@jderr-mx we've had this problem before but I don't remember the resolution. I'm not too fond of putting it in the exceptions file :\ Let me investigate a bit before merging.

**Comment by locks** [comment]
Thanks for your contribution!

**Pull request merged**
