### PR TITLE
Update installing-addons.md

### PR DESCRIPTION
**Pull request by adrianbw**
Fix typo.

### CODE REVIEW

**Comment by acorncom** [comment]
Thanks @adrianbw but the base command is actually `serve` 😀  The default is `serve` with `server` or `s` being aliases (see https://github.com/ember-cli/ember-cli/blob/master/lib/commands/serve.js#L20) We've had this type of PR sent in before 😉

**Comment by adrianbw** [comment]
How about updating the tutorials to use `ember serve` instead of `ember server`, then? If you've done nothing but the tutorials (which I'd assume is the case here), then this is pretty confusing (in fact, it was so "obviously" a typo that I didn't see a reason to search for it).

**Comment by acorncom** [comment]
Ah, are they mixed? That is indeed confusing. Yes, we'll get that fixed one way or another. Thanks for pointing it out!

**Comment by adrianbw** [comment]
Yeah. I'll take care of it as I go through the tutorial.

**Comment by acorncom** [comment]
@toddjordan @locks Which command do you think we should be defaulting to? I'm inclined toward `ember serve` instead of `ember server`, mainly because it might help it seem less like "Ember has a server I should be running in production". Thoughts?

**Comment by locks** [comment]
We're normalizing everything to `ember serve`, since it's the base command.

**Pull request closed without merging**
