### PR TITLE
Remove references to {{render}} and {{partial}}

### PR DESCRIPTION
**Pull request by HeroicEric**
fixes https://github.com/emberjs/guides/issues/498

- [x] Remove /templates/rendering-with-helpers/
- [x] Audit for any usages of `{{render}}`
- [x] Audit for any usages of `{{partial}}`

I didn't replace that JSBin with one that uses components because of the other issue for removing all the JSBins.

### CODE REVIEW

**Comment by rwjblue** [comment]
CI build failed (I submitted https://github.com/emberjs/guides/pull/503 to make the output more useful), can you take a look at `middleman build --verbose` and see what it is barking about?

**Comment by HeroicEric** [comment]
There are still references to [renderTemplate](http://emberjs.com/api/classes/Ember.Route.html#method_renderTemplate) in [/routing/rendering-a-template](https://github.com/HeroicEric/guides/blob/remove-render-and-partial/source/routing/rendering-a-template.md) but I assume those should stick around?

**Comment by rwjblue** [comment]
yeah, `renderTemplate` is a `Ember.Route` API that will remain (it is unrelated to the `{{render}}` helper).

**Comment by HeroicEric** [comment]
@rwjblue build failure was because of `data/pages.yml`. Removing the entry for the page that I removed fixed it.

**Pull request merged**
