### PR TITLE
Document Ember.Service

### PR DESCRIPTION
**Pull request by bf4**
stubbing something for discussion

### CODE REVIEW

**Comment by bf4** [comment]
@mitchlloyd @rwjblue any feedback on what should go in the guides here appreciated.  I haven't actually used a service before.

**Comment by mitchlloyd** [comment]
@bf4 Reading over the current document, it seems like there needs to be a pretty big overhaul. Probably the documentation needs to go something like this:

* What is dependency injection?
  - Example of route getting the router injected should be updated for routing service, but that depends on https://github.com/emberjs/ember.js/pull/10596
* What is a service and what is it good for? (use cases, audio example in here is good but needs to be updated to use a service and not use `render`)
* Using Ember.inject to inject services (and controllers I suppose)
* Ember's register & inject (what is there appears valid)

**Comment by bf4** [comment]
@mitchlloyd If you're up to writing it, I can close this. I really just wanted to start a discussion and maybe learn a thing or two.

I don't think I have enough context or experience to expand on your bullet points in any useful way. :smile: If you want  to collaborate in code, I suppose you can open a PR into my branch.

**Comment by mitchlloyd** [comment]
I think there just needs to be an issue to document services if there isn't
one already. I have had many people ask me "where are services documented"?

**Comment by bf4** [comment]
I decided to make the issue as a PR in case that it was close to what I wrote that I could take it home.  (I also prefer PRs to 'hey could you do this?' :)

**Comment by locks** [comment]
@bf4 can you close this? like @mitchlloyd commented it's not a light undertaking and it's easier to coordinate internally

**Pull request closed without merging**
