### PR TITLE
[FIX] Input helpers page links to deprecated API

### LINKED ISSUE #1901: Input helpers page links to deprecated API
In the EmberJS 2.12.0 Guides' [section regarding](https://github.com/emberjs/guides/blob/master/source/localizable/templates/input-helpers.md#actions) [input helpers](https://guides.emberjs.com/v2.12.0/templates/input-helpers/) there appears to be a link to a private, deprecated API.

> [Event Names](https://emberjs.com/api/classes/Ember.View.html#toc_event-names) must be dasherized.

Should these event names no longer be used or are they just part of some other interface now?

### PR DESCRIPTION
**Pull request by alexdiliberto**
Closes #1901

### CODE REVIEW

**Comment by locks** [comment]
Hi @alexdiliberto, thank you very much for your contributions! I do have a small request, however. Can you submit changes only to the source English document? The translation service will synchronise the changes afterwards.

**Comment by alexdiliberto** [comment]
@locks Sure thing! fixed on all 3 of my commits

**Comment by locks** [comment]
👌  Thank you for the contribution.
@homu r+

**Comment by locks** [comment]
@homu r+

**Comment by locks** [comment]
@homu retry

**Pull request merged**
