### PR TITLE
[WIP] Style redesign

### PR DESCRIPTION
**Pull request by locks**
- [x] Port over [thoughtbot/ember-guides/](https://github.com/thoughtbot/ember-guides/)
- [x] Tweak contrast
- [x] Tweak structure
- [x] Tweak header
- [x] Fix sidebar/content layout
- [x] Keep old code sample styling, but move flag to the path name
- [x] Clean up paragraph and color CSS
- [x] Swap footer back to old footer (for now)
- [ ] Test in browsers
  - [x] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] Shiira
  - [ ] Camino
  - [ ] Mobile

### CODE REVIEW

**Comment by josemarluedke** [comment]
@locks What can we do to help you on this issue?

**Comment by locks** [comment]
@josemarluedke not much at the moment, I just have to finishing some grunt work.

**Comment by stefanpenner** [comment]
can you post a screenshot.

**Comment by locks** [comment]
work in progress of the redesign

A bunch of work yet to be done :x

**Comment by locks** [comment]
Here's the redesign as implemented by thoughtbot:

screen shot 2015-09-20 at 23 08 47

**Comment by acorncom** [comment]
[ ] fix the HTML .svg file to be in color (it's black right now).  Match the light pink in the `source/img/html-ribbon.png`

**Comment by michaelrkn** [comment]
Just took a look and everything seems nice to me! The only thing is that it feels like there is a lot of unnecessary vertical space between block elements - @locks you mentioned that maybe that's from the old CSS? Maybe the CSS cleanup should happen as part of this PR?

**Comment by locks** [comment]
Yup yup, there's also some text color issues to clean up

**Comment by acorncom** [comment]
Once we've got the reworked H1-H3 tags in, I think we should merge this.  It's looking fairly sharp.  @josemarluedke thanks for all the help!

**Comment by acorncom** [comment]
Our header is currently fairly badly broken when viewed using Safari 9.0  Looks like the SVG setup isn't playing nicely with it at all ...

screen shot 2015-11-10 at 5 52 28 pm

@josemarluedke Is that something you'd be able to take a look at?  I'm pretty swamped at the moment :-/

**Comment by acorncom** [comment]
Never mind, turns out it was a floating point issue that Chrome handled but Safari couldn't.  Just sent in a pull request on that.

**Comment by wifelette** [comment]
I’m thinking we should move the little JS and HBS tags to always be on the body, not the header—because only some things ​_have_​ headers, so it’ll be more visually consistent. 

Thoughts? Could this create issues with code running long and overlapping with the label or anything like that?

**Comment by tomdale** [comment]
@locks Pushed a commit with the implemented footer. ^^

**Comment by tomdale** [comment]
@wifelette @locks @michaelrkn @trek What do we need to do to get this merged and deployed?

**Comment by michaelrkn** [comment]
I believe at this point the only thing left is for @locks to rebase, maybe squash a couple commits, and fix a couple commits/commit messages.

**Comment by locks** [comment]
:shipit:

**Comment by michaelrkn** [comment]
Travis couldn't build because some gem got updated that needs Ruby 2.0. I updated Ruby but now a couple specs are failing. I'll try to look into this later but it might be a day or two before I have time.

**Comment by tomdale** [comment]
@michaelrkn Thanks for looking into that. I was very curious about why our tests were failing. I'm surprised the `Gemfile.lock` didn't prevent this issue?

**Comment by michaelrkn** [comment]
@tomdale I think some deps got updated as part of adding bourbon, neat, and normalize.

**Comment by michaelrkn** [comment]
I've got the gems sorted out so that 1.9.3 works, but those specs are still failing.

**Comment by acorncom** [comment]
@michaelrkn If my pull request tests pass then we should have tests passing again here

**Comment by michaelrkn** [comment]
Hrm, still failing. It's choking on:

```
Sass::SyntaxError: File to import not found or unreadable: normalize.
Load paths:
  /Users/michael/Code/guides/source/stylesheets
  /Users/michael/.gem/ruby/2.2.2/gems/compass-core-1.0.3/stylesheets
  Compass::SpriteImporter
  /Users/michael/.gem/ruby/2.2.2/gems/bourbon-4.2.6/app/assets/stylesheets
  /Users/michael/.gem/ruby/2.2.2/gems/neat-1.7.2/app/assets/stylesheets
  (in /Users/michael/Code/guides/source/stylesheets/application.css.scss:3)
```

I tried adding `require "normalize-scss"` to `config.rb` but it did not help.

@acorncom any ideas?

**Comment by acorncom** [comment]
Hmm, not at the moment.  Will see if I can get to this sometime soon (but if someone else wants to beat me, go for it ;-)

**Comment by michaelrkn** [comment]
Okay, I've fixed it. @acorncom or @locks, can one of you do one last sanity check and then merge?

**Comment by acorncom** [comment]
I fixed a few bugs (more notes on them in the commit above), but this is ready to go in.  Merging ...

**Comment by michaelrkn** [comment]
:tada:

**Comment by josemarluedke** [comment]
:tada: :tada:

**Pull request merged**
