### PR TITLE
updated relationships.md | ES6 syntax

### PR DESCRIPTION
**Pull request by rahulsingh-js**
Modified docs according to ES6+ standards.

### CODE REVIEW

**Comment by jenweber** [comment]
Hi @rahulsingh-js, thanks for pitching in! However we are moving the guides over to a new repository very shortly, which means that significant changes to content should be PR'd there. Please see the README for more details. Sorry for the inconvenience. I also recommend opening an issue before doing too much coding, so that we can coordinate a list of places that need to be changed, as well as get team consensus on the switch. Thank you!

**Comment by jenweber** [comment]
Awesome! Here are the links: 
- https://github.com/ember-learn/guides-source
- https://github.com/ember-learn/guides-app

As I mentioned in the other comment, I'd like to get an entry into the JavaScript Primer before we change over a bunch of things into arrow functions. I do agree we need to do the conversion though.

**Comment by rahulsingh-js** [comment]
Thanks for sharing

**Comment by sivakumar-kailasam** [comment]
Closing based on @jenweber's comments

**Pull request closed without merging**
