### PR TITLE
Fix reference-style links

### PR DESCRIPTION
**Pull request by fsoumare**
Links on the following pages point to wrong sections of the api doc:
https://guides.emberjs.com/v2.3.0/object-model/bindings/
https://guides.emberjs.com/v2.3.0/object-model/enumerables/
https://guides.emberjs.com/v2.3.0/object-model/observers/
https://guides.emberjs.com/v2.3.0/routing/asynchronous-routing/

### CODE REVIEW

**Comment by locks** [comment]
@fsoumare can you do me a favour and inline the links instead? I've found that using footnote-style links has been leading to problems with the references getting out of sync or wrong.

**Comment by fsoumare** [comment]
Done. I think we should use inline links throughout the docs. I can give a hand if need be.

**Comment by acorncom** [comment]
@fsoumare if you wouldn't mind helping run through to adjust those, it would be much appreciated. I tried the other approach because it looked cleaner but it's been a headache :-/

For this PR, could you squash your commits? Once you have we'll get it merged :-)

**Comment by fsoumare** [comment]
Looks like I didn't squash my commits properly. Shall I create a new PR with a single commit?

**Comment by locks** [comment]
@fsoumare it's probably the more straightforward way, so you don't have to much too much with git. go ahead :)

**Comment by fsoumare** [comment]
How about now? :)

**Comment by acorncom** [comment]
@homu r+

Looks good!

**Pull request merged**
