### PR TITLE
[WIP] Add a helpers tutorial

### PR DESCRIPTION
**Pull request by davewasmer**
Adds a short helpers page to the tutorial, courtesy of the Denver Ember meetup [Project Night](http://www.meetup.com/Ember-js-Denver/events/226475514/)

### CODE REVIEW

**Comment by acorncom** [comment]
Helps with #801

**Comment by locks** [comment]
You need to add it to the TOC

**Comment by acorncom** [comment]
@locks I'll probably be taking over on this from here, this was part of what our meetup group worked on last night.

**Comment by acorncom** [comment]
Closing in favor of #1102

**Pull request closed without merging**
