### PR TITLE
Search improvements

### PR DESCRIPTION
**Pull request by acorncom**
- [x] Pending latest version of the guides being indexed on Algolia's end

### CODE REVIEW

**Comment by acorncom** [comment]
Supersedes #1202 and #1199

**Comment by acorncom** [comment]
@locks @toddjordan This is ready for review.  One thing to note (that differs from our current setup and that we may want to handle before we merge this).

Algolia does search indexing *post*-deploy.  We've got a few options for handling that:

- per their suggestion: "if you could provide us a public beta version of this new doc, we could index it before the official release".  This would only work if we're deploying at the appropriate location (i.e. `/v2.6/`) but don't enable it for all visitors to see (primarily our `firebase.json` file and our `versions.json` file).  We can't have them index the beta site, as the index contains the page url and if that's not accurate, we'll end up with very confused visitors ;-)
- leave search broken for the 1 day window (or so) that it takes for them to re-index
- jury-rig something else?

Thoughts here?

**Comment by locks** [comment]
> leave search broken for the 1 day window (or so) that it takes for them to re-index

**Comment by acorncom** [comment]
Then we are ready to merge here.  Would suggest we deploy soon so we can iron out the bugs prior to 2.6 release

**Comment by toddjordan** [comment]
@acorncom LGTM 👍 I'll let @locks merge 💥  🔫

**Comment by locks** [comment]
@toddjordan go ahead, I don't mind :trollface:

**Comment by locks** [comment]
@toddjordan @acorncom 2.6 is releasing today

**Comment by acorncom** [comment]
This is back to pending while I wait to hear from the Algolia folks about a slight tweak they've made on their end.  Once that's in, I'll merge this

**Comment by acorncom** [comment]
@homu r+

**Pull request merged**
