### PR TITLE
Remove `px` from <img> width attribute

### PR DESCRIPTION
**Pull request by jsmestad**
As suggested by HTML Tidy. According to MDN reference, the width attribute assumes pixels without a unit. [ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img)

### CODE REVIEW

**Comment by jsmestad** [comment]
Fixed.

**Comment by locks** [comment]
@homu r+

**Comment by jsmestad** [comment]
Not sure how to resolve the squashing failure. Tips?

**Comment by locks** [comment]
@jsmestad can you reach me in #documentation on Slack?

**Pull request closed without merging**
