### PR TITLE
[WIP] Remove negative margin causing glitch on hover

### PR DESCRIPTION
**Pull request by miguelmota**
Bug
sidebar-glitch

### CODE REVIEW

**Comment by acorncom** [comment]
I'm pretty sure I remember that being added deliberately ;-)  See https://github.com/emberjs/guides/pull/1179 for details.  Any suggestions on how to fix that more permanently?  Seems like we might be stuck with it being a tad glitchy somewhere ...

**Comment by locks** [comment]
@ryanlabouve can you give this a review?

**Comment by kpfefferle** [comment]
(I made the previous PR #1179)

The addition of the negative margin fixes the unselected case, but I see why it's breaking the selected case. I will spin up an adjustment that can handle both cases. The key thing is that we don't want the item width to change in either case. The proposal to remove the negative margin returns us to both cases potentially suffering from this problem.

**Comment by kpfefferle** [comment]
I've been playing around with this for a bit, and the behavior on that element is even glitchier in my browser:

old

This seems to be happening because we are animating both the border-width on the left (from 3px to 6px) and the margin on the right (from 0 to -3px to offset the increased border-width). Depending on how the browser handles the animation of these two properties, the width of the element (and thus the text wrapping) varies during animation and causes this glitchy behavior.

I'm going to keep investigating how we might resolve this.

**Comment by ryanlabouve** [comment]
@locks sure thing!

I'm wondering if we might use a psuedo element and animate the width on that instead of using margins at all. That way the text should not be affected at all.

@kpfefferle let me know if you'd like to take run at it! I'm happy to work on this.

**Comment by kpfefferle** [comment]
@ryanlabouve If you have time, feel free. I'm not sure when I'd be able to loop back around and look at it.

**Comment by acorncom** [comment]
Marking this WIP for now

**Comment by acorncom** [comment]
I'm going to close this for now due to lack of activity, but happy to open it again if folks want to work on this more ...

**Pull request closed without merging**
